site_name: LUST-motion

nav:
  - Home: index.md
  - "Make It":
      - make-it/flashfirmware.md
  - "Use It":
      - "Important Safety Notes":
          - use-it/safety.md
      - "User Guide":
          - use-it/quickstart.md
          - use-it/usage.md
          - use-it/pattern.md
          - use-it/settings.md
      - "Advanced User Guide":
          - use-it/configuration.md
          - use-it/connectivity.md
          - use-it/API.md
  - "Hack It":
      - "Firmware":
          - hack-it/buildfirmware.md
          - hack-it/structure.md
      - "Pattern":
          - hack-it/addpattern.md
          - hack-it/testpattern.md

site_author: elims
site_description: >-
  Noisy Cricket is a small (wearable) e-stim development board which packs quite a punch.

# Repository
repo_name: openlust/LUST-motion
repo_url: https://github.com/openlust/LUST-motion

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: indigo

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openlust
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

copyright: |
  Copyright &copy; 2025 by <a href="https://github.com/openlust"  target="_blank" rel="noopener">elims</a> -
  <a href="#__consent">Change cookie settings</a>
